apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base/cnpg
  - ../base/immich
  - ../base/linkding

patches:
  - patch: |-
      apiVersion: v1
      kind: Pod
      metadata:
        name: ts-linkding
      spec:
        containers:
        - name: tailscale
          env:
          - name: TS_DEST_IP
            value: "10.43.146.57"
    target:
      kind: Pod
      name: ts-linkding
  - patch: |-
      apiVersion: v1
      kind: PersistentVolume
      metadata:
        name: immich-ml-pv
      spec:
        hostPath:
          path: "/mnt/ssd/apps/immich/ml-pv"
  - patch: |-
      apiVersion: v1
      kind: PersistentVolume
      metadata:
        name: immich-library-pv
      spec:
        capacity:
          storage: 1000Gi
        hostPath:
          path: "/mnt/ssd/apps/immich/library-pv"
  - patch: |-
      $patch: delete
      apiVersion: helm.toolkit.fluxcd.io/v2
      kind: HelmRelease
      metadata:
        name: immich
        namespace: immich
