apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base/cnpg
  - ../base/linkding

patches:
  - patch: |-
      apiVersion: v1
      kind: Pod
      metadata:
        name: ts-linkding
      spec:
        containers:
        - name: tailscale
          env:
          - name: TS_DEST_IP
            value: "10.43.146.57"
    target:
      kind: Pod
      name: ts-linkding
