apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: immich
  namespace: immich
spec:
  interval: 10m
  chart:
    spec:
      chart: immich-0.9.3
      version: 'v1.119.0'
      sourceRef:
        kind: HelmRepository
        name: immich
        namespace: immich
      interval: 10m
  valuesFrom:
    - kind: ConfigMap
      name: immich-values
