namespace: immich
resources:
  - helm-repository-cnpg.yaml
  - pg.yaml
  - helm-repository.yaml
  - helm-release.yaml
configMapGenerator:
  - name: immich-values
    files:
      - values.yaml
configurations:
  - kustomizeconfig.yaml
