env:
  - name: REDIS_HOSTNAME
    value: '{{ printf "%s-redis-master" .Release.Name }}'
  - name: DB_HOSTNAME
    value: "{{ .Release.Name }}-postgres-rw.immich.svc.cluster.local"
  - name: DB_USERNAME
    valueFrom:
      secretKeyRef:
        name: immich-postgres-user
        key: DB_USERNAME
  - name: DB_DATABASE_NAME
    valueFrom:
      secretKeyRef:
        name: immich-postgres-user
        key: DB_DATABASE_NAME
  - name: DB_PASSWORD
    valueFrom:
      secretKeyRef:
        name: immich-postgres-user
        key: DB_PASSWORD
  - name: IMMICH_MACHINE_LEARNING_URL
    value: '{{ printf "http://%s-machine-learning:3003" .Release.Name }}'
 
image:
  tag: v1.135.3
 
immich:
  metrics:
    enabled: false
  persistence:
    library:
      existingClaim: immich-library-pvc
  configuration: {}
  
# Dependencies
redis:
  enabled: true
  architecture: standalone
  auth:
    enabled: false
 
# Immich components
server:
  enabled: true
  image:
    repository: ghcr.io/immich-app/immich-server
    pullPolicy: IfNotPresent
  ingress:
    main:
      enabled: true
      annotations:
        traefik.ingress.kubernetes.io/service.nativelb: "true"
        traefik.ingress.kubernetes.io/service.sticky.cookie: "true"
      hosts:
        - host: immich.kube
          paths:
            - path: "/"
      tls: []
 
machine-learning:
  enabled: true
  image:
    repository: ghcr.io/immich-app/immich-machine-learning
    pullPolicy: IfNotPresent
  env:
    TRANSFORMERS_CACHE: /cache
  persistence:
    cache:
      enabled: true
      size: 10Gi
      existingClaim: immich-ml-pvc
