apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base/cnpg
  - ../base/immich
  - ../base/linkding

patches:
  - patch: |-
      apiVersion: v1
      kind: Pod
      metadata:
        name: ts-linkding-dev
      spec:
        containers:
        - name: tailscale
          env:
          - name: TS_DEST_IP
            value: "10.43.209.1"
    options:
      allowNameChange: true
    target:
      kind: Pod
      name: ts-linkding
  - patch: |-
      $patch: delete
      apiVersion: helm.toolkit.fluxcd.io/v2
      kind: HelmRelease
      metadata:
        name: immich
        namespace: immich
