namespace: default
resources:
  - pvc.yaml
  - deploy.yaml
  - service.yaml
  - ../tailscale-rbac
  - ../tailscale-proxy

patches:
  - patch: |-
      [
        {"op": "replace",
         "path": "/metadata/name",
         "value": "ts-linkding"}
      ]
    target:
      kind: Pod
      name: proxy
