apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cnpg
  namespace: flux-system
spec:
  interval: 1m
  path: ./kubernetes-homelab/apps/cnpg
  prune: false
  sourceRef:
    kind: GitRepository
    name: flux-system
  targetNamespace: cnpg-system
  timeout: 2m
