apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: immich
  namespace: flux-system
spec:
  interval: 1m
  path: ./kubernetes-homelab/apps/immich
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  targetNamespace: immich
  timeout: 2m
