apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: linkding
  namespace: flux-system
spec:
  interval: 1m
  path: ./kubernetes-homelab/apps/linkding
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  targetNamespace: default
  timeout: 2m
